### ISSUE TITLE
saveAs undefined

### ISSUE THREAD

**Issue by jgdovin** [pfafman/meteor-filesaver#1]
I am relying on your package for my html-pdf package in meteor. For some reason the update you did today makes it so that saveAs is not defined in the browser. I haven't taken the time to figure out the cause of this just yet but can look into it in a few.

I am using Google Chrome Version 42.0.2311.90

After adding pfafman:filesaver to project and restarting with version 0.2.0 saveAs in console is undefined. revert to 0.1.0 and saveAs is accessible.

**Comment by pfafman** [comment]
I forgot to attach it to the window object.  See if it works now

**Comment by pfafman** [comment]
closing
